### ISSUE TITLE
aktuelle Version stürzt beim Starten ab (Samsung Galaxy S2, Android )

### ISSUE THREAD

**Issue by fama-berlin** [immopoly/immopoly#37]
Hallo zusammen,

ich (toram) nutze momentan eine apk, die ich am 20.07. heruntergeladen habe (185,1 KB). Die neuere Version (letzter Download am 10.09., Größe 202,6 KB) stürzt beim Laden ab.

Die Fehlermeldung als Screenshot: http://img196.imageshack.us/img196/2994/sc201109111718191.jpg

**Comment by fama-berlin** [comment]
Android in der Überscsrift soll "Android 2.3.3" heißen ;-)

**Comment by FreXxX** [comment]
Moin,

habe soeben (12. September, 6:20) die neuste Version (1.2) herunter geladen.
Crasht auch direkt beim Start. 

HTC Hero, Custom ROM inkl OC, Android 2.2.1

Wäre es möglich, die aktuelle Version immer inkl Versionsnummer zu verlinken, und auf ner Untersite die alten Versionen auch noch zum Download zu bieten?

"Die aktuelle Version der Android App finden Sie hier: Immopoly.apk (Version 1.2)

Ältere Versionen gibt es hier: Immopoly.apk (Version 1.1) Immopoly.apk (Version 1.0)" oder ähnlich.

Bei Bedarf kann ich Logfiles nachreichen. 

Langt das hier?

09-12 06:25:35.664 I/ActivityManager(124)Displayed activity de.tosa.findAFlat/.UserSignupActivity: 1387 ms (total 1387 ms)
09-12 06:25:35.754 D/LocationMasfClient(124)getNetworkLocation(): Returning cache location with accuracy 1480.0
09-12 06:25:35.944 D/LocationMasfClient(124)getNetworkLocation(): Returning cache location with accuracy 1480.0
09-12 06:25:36.854 D/dalvikvm(6603)GC_FOR_MALLOC freed 2671 objects / 331112 bytes in 83ms
09-12 06:25:37.244 I/Database(6603)sqlite returned: error code = 1, msg = no such column: flat_lat
09-12 06:25:37.254 W/dalvikvm(6603)threadid=8: thread exiting with uncaught exception (group=0x40020800)
09-12 06:25:37.274 E/AndroidRuntime(6603)FATAL EXCEPTION: AsyncTask #1
09-12 06:25:37.274 E/AndroidRuntime(6603)java.lang.RuntimeException: An error occured while executing doInBackground()
09-12 06:25:37.274 E/AndroidRuntime(6603)at android.os.AsyncTask$3.done(AsyncTask.java:200)
09-12 06:25:37.274 E/AndroidRuntime(6603)at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
09-12 06:25:37.274 E/AndroidRuntime(6603)at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
09-12 06:25:37.274 E/AndroidRuntime(6603)at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
09-12 06:25:37.274 E/AndroidRuntime(6603)at java.util.concurrent.FutureTask.run(FutureTask.java:137)
09-12 06:25:37.274 E/AndroidRuntime(6603)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1068)
09-12 06:25:37.274 E/AndroidRuntime(6603)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:561)
09-12 06:25:37.274 E/AndroidRuntime(6603)at java.lang.Thread.run(Thread.java:1096)
09-12 06:25:37.274 E/AndroidRuntime(6603)Caused by: android.database.sqlite.SQLiteException: no such column: flat_lat: , while compiling: SELECT flat_name, flat_lat, _id, flat_description, flat_lng FROM flats
09-12 06:25:37.274 E/AndroidRuntime(6603)at android.database.sqlite.SQLiteCompiledSql.native_compile(Native Method)
09-12 06:25:37.274 E/AndroidRuntime(6603)at android.database.sqlite.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
09-12 06:25:37.274 E/AndroidRuntime(6603)at android.database.sqlite.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
09-12 06:25:37.274 E/AndroidRuntime(6603)at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:80)
09-12 06:25:37.274 E/AndroidRuntime(6603)at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:46)
09-12 06:25:37.274 E/AndroidRuntime(6603)at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
09-12 06:25:37.274 E/AndroidRuntime(6603)at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1345)
09-12 06:25:37.274 E/AndroidRuntime(6603)at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:330)
09-12 06:25:37.274 E/AndroidRuntime(6603)at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:280)
09-12 06:25:37.274 E/AndroidRuntime(6603)at de.tosa.findAFlat.provider.FlatsProvider.query(FlatsProvider.java:151)
09-12 06:25:37.274 E/AndroidRuntime(6603)at android.content.ContentProvider$Transport.query(ContentProvider.java:186)
09-12 06:25:37.274 E/AndroidRuntime(6603)at android.content.ContentResolver.query(ContentResolver.java:250)
09-12 06:25:37.274 E/AndroidRuntime(6603)at de.tosa.findAFlat.tasks.GetUserInfoTask.doInBackground(GetUserInfoTask.java:53)
09-12 06:25:37.274 E/AndroidRuntime(6603)at de.tosa.findAFlat.tasks.GetUserInfoTask.doInBackground(GetUserInfoTask.java:1)
09-12 06:25:37.274 E/AndroidRuntime(6603)at android.os.AsyncTask$2.call(AsyncTask.java:185)
09-12 06:25:37.274 E/AndroidRuntime(6603)at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
09-12 06:25:37.274 E/AndroidRuntime(6603)... 4 more
09-12 06:25:37.294 W/ActivityManager(124)Force finishing activity de.tosa.findAFlat/.UserSignupActivity
09-12 06:25:38.954 I/Process (6603)Sending signal. PID: 6603 SIG: 9
09-12 06:25:39.164 I/ActivityManager(124)Process de.tosa.findAFlat (pid 6603) has died.

**Comment by mrschtief** [comment]
hey danke für den Report, wir sind gerade ordentlich am umstricken der App und sagen euch bescheid sobald es eine nächste preMarket Version gibt. Danke schonmal fürs Testen

**Comment by mrschtief** [comment]
es hat sich rausgestellt, dass es an einem fehlerhaften update zwischen den letzten Versionen lag. wenn man neu installiert geht es wieder
